// This page will be hard coded for now to only handle MLB score results from the MLB API.
"use client"; // haven't completely figured out best way to use client vs server components in nextjs just yet, probably just need a different component.

import { useCallback, useEffect, useState } from "react";
import ScoreItem from "./scoreitem";

import styles from "./scoretable.module.css";

const ScoreTable = (props) => {
  const [scores, setScores] = useState([]);

  const { league, date, verbosity } = props;

  // This will be commented out till the JSON files are corretly parsed. Dummy Date will be used for now.
  const [error, setError] = useState(null);

  const fetchScores = useCallback(async () => {
    try {
      const response = await fetch(
        `/api/mlb/schedule/${date}`
      );

      if (!response.ok) {
        throw new Error("Scores could not get retrieved!");
      }
      // const data = await response.json(); ORIGINAL CODE

      // DUMMY DATA - DELETE LATER
      const data = [
        {
            "away_id": 119,
            "away_name": "Los Angeles Dodgers",
            "away_pitcher_note": "",
            "away_probable_pitcher": "Caleb Ferguson",
            "away_score": 1,
            "current_inning": 9,
            "doubleheader": "S",
            "game_date": "2023-09-26",
            "game_datetime": "2023-09-26T19:10:00Z",
            "game_id": 716438,
            "game_num": 1,
            "game_type": "R",
            "home_id": 115,
            "home_name": "Colorado Rockies",
            "home_pitcher_note": "",
            "home_probable_pitcher": "Chase Anderson",
            "home_score": 4,
            "inning_state": "Top",
            "losing_pitcher": "Caleb Ferguson",
            "losing_team": "Los Angeles Dodgers",
            "national_broadcasts": [
                "MLBN (out-of-market only)"
            ],
            "save_pitcher": "Tyler Kinley",
            "series_status": "COL leads 1-0",
            "status": "Final",
            "summary": "2023-09-26 - Los Angeles Dodgers (1) @ Colorado Rockies (4) (Final)",
            "venue_id": 19,
            "venue_name": "Coors Field",
            "winning_pitcher": "Chase Anderson",
            "winning_team": "Colorado Rockies"
        },
        {
            "away_id": 119,
            "away_name": "Los Angeles Dodgers",
            "away_pitcher_note": "",
            "away_probable_pitcher": "Bobby Miller",
            "away_score": 0,
            "current_inning": 1,
            "doubleheader": "S",
            "game_date": "2023-09-26",
            "game_datetime": "2023-09-27T00:40:00Z",
            "game_id": 716424,
            "game_num": 2,
            "game_type": "R",
            "home_id": 115,
            "home_name": "Colorado Rockies",
            "home_pitcher_note": "",
            "home_probable_pitcher": "Ryan Feltner",
            "home_score": 0,
            "inning_state": "Top",
            "national_broadcasts": [],
            "series_status": "COL leads 1-0",
            "status": "Pre-Game",
            "summary": "2023-09-26 - Los Angeles Dodgers @ Colorado Rockies (Pre-Game)",
            "venue_id": 19,
            "venue_name": "Coors Field"
        },
        {
            "away_id": 113,
            "away_name": "Cincinnati Reds",
            "away_pitcher_note": "",
            "away_probable_pitcher": "Hunter Greene",
            "away_score": 5,
            "current_inning": 4,
            "doubleheader": "N",
            "game_date": "2023-09-26",
            "game_datetime": "2023-09-26T22:10:00Z",
            "game_id": 716435,
            "game_num": 1,
            "game_type": "R",
            "home_id": 114,
            "home_name": "Cleveland Guardians",
            "home_pitcher_note": "",
            "home_probable_pitcher": "Lucas Giolito",
            "home_score": 7,
            "inning_state": "Bottom",
            "national_broadcasts": [],
            "series_status": null,
            "status": "In Progress",
            "summary": "2023-09-26 - Cincinnati Reds (5) @ Cleveland Guardians (7) (Bottom of the 4th)",
            "venue_id": 5,
            "venue_name": "Progressive Field"
        },
        {
            "away_id": 120,
            "away_name": "Washington Nationals",
            "away_pitcher_note": "",
            "away_probable_pitcher": "Josiah Gray",
            "away_score": 0,
            "current_inning": 5,
            "doubleheader": "N",
            "game_date": "2023-09-26",
            "game_datetime": "2023-09-26T22:35:00Z",
            "game_id": 716434,
            "game_num": 1,
            "game_type": "R",
            "home_id": 110,
            "home_name": "Baltimore Orioles",
            "home_pitcher_note": "",
            "home_probable_pitcher": "Kyle Bradish",
            "home_score": 1,
            "inning_state": "Top",
            "national_broadcasts": [],
            "series_status": null,
            "status": "In Progress",
            "summary": "2023-09-26 - Washington Nationals (0) @ Baltimore Orioles (1) (Top of the 5th)",
            "venue_id": 2,
            "venue_name": "Oriole Park at Camden Yards"
        },
        {
            "away_id": 118,
            "away_name": "Kansas City Royals",
            "away_pitcher_note": "",
            "away_probable_pitcher": "Zack Greinke",
            "away_score": 1,
            "current_inning": 4,
            "doubleheader": "N",
            "game_date": "2023-09-26",
            "game_datetime": "2023-09-26T22:40:00Z",
            "game_id": 716433,
            "game_num": 1,
            "game_type": "R",
            "home_id": 116,
            "home_name": "Detroit Tigers",
            "home_pitcher_note": "",
            "home_probable_pitcher": "Reese Olson",
            "home_score": 0,
            "inning_state": "Bottom",
            "national_broadcasts": [],
            "series_status": null,
            "status": "In Progress",
            "summary": "2023-09-26 - Kansas City Royals (1) @ Detroit Tigers (0) (Bottom of the 4th)",
            "venue_id": 2394,
            "venue_name": "Comerica Park"
        },
        {
            "away_id": 134,
            "away_name": "Pittsburgh Pirates",
            "away_pitcher_note": "",
            "away_probable_pitcher": "Mitch Keller",
            "away_score": 0,
            "current_inning": 5,
            "doubleheader": "N",
            "game_date": "2023-09-26",
            "game_datetime": "2023-09-26T22:40:00Z",
            "game_id": 716432,
            "game_num": 1,
            "game_type": "R",
            "home_id": 143,
            "home_name": "Philadelphia Phillies",
            "home_pitcher_note": "",
            "home_probable_pitcher": "Aaron Nola",
            "home_score": 0,
            "inning_state": "Bottom",
            "national_broadcasts": [],
            "series_status": null,
            "status": "In Progress",
            "summary": "2023-09-26 - Pittsburgh Pirates (0) @ Philadelphia Phillies (0) (Bottom of the 5th)",
            "venue_id": 2681,
            "venue_name": "Citizens Bank Park"
        },
        {
            "away_id": 147,
            "away_name": "New York Yankees",
            "away_pitcher_note": "",
            "away_probable_pitcher": "Michael King",
            "away_score": 0,
            "current_inning": 3,
            "doubleheader": "N",
            "game_date": "2023-09-26",
            "game_datetime": "2023-09-26T23:07:00Z",
            "game_id": 716431,
            "game_num": 1,
            "game_type": "R",
            "home_id": 141,
            "home_name": "Toronto Blue Jays",
            "home_pitcher_note": "",
            "home_probable_pitcher": "Kevin Gausman",
            "home_score": 0,
            "inning_state": "Bottom",
            "national_broadcasts": [],
            "series_status": null,
            "status": "In Progress",
            "summary": "2023-09-26 - New York Yankees (0) @ Toronto Blue Jays (0) (Bottom of the 3rd)",
            "venue_id": 14,
            "venue_name": "Rogers Centre"
        },
        {
            "away_id": 139,
            "away_name": "Tampa Bay Rays",
            "away_pitcher_note": "",
            "away_probable_pitcher": "Zach Eflin",
            "away_score": 3,
            "current_inning": 2,
            "doubleheader": "N",
            "game_date": "2023-09-26",
            "game_datetime": "2023-09-26T23:10:00Z",
            "game_id": 716428,
            "game_num": 1,
            "game_type": "R",
            "home_id": 111,
            "home_name": "Boston Red Sox",
            "home_pitcher_note": "",
            "home_probable_pitcher": "Tanner Houck",
            "home_score": 0,
            "inning_state": "Bottom",
            "national_broadcasts": [],
            "series_status": null,
            "status": "In Progress",
            "summary": "2023-09-26 - Tampa Bay Rays (3) @ Boston Red Sox (0) (Bottom of the 2nd)",
            "venue_id": 3,
            "venue_name": "Fenway Park"
        },
        {
            "away_id": 146,
            "away_name": "Miami Marlins",
            "away_pitcher_note": "",
            "away_probable_pitcher": "Braxton Garrett",
            "away_score": 0,
            "current_inning": 1,
            "doubleheader": "N",
            "game_date": "2023-09-26",
            "game_datetime": "2023-09-26T23:10:00Z",
            "game_id": 716430,
            "game_num": 1,
            "game_type": "R",
            "home_id": 121,
            "home_name": "New York Mets",
            "home_pitcher_note": "",
            "home_probable_pitcher": "Joey Lucchesi",
            "home_score": 0,
            "inning_state": "Top",
            "national_broadcasts": [],
            "series_status": null,
            "status": "Delayed Start: Wet Grounds",
            "summary": "2023-09-26 - Miami Marlins @ New York Mets (Delayed Start: Wet Grounds)",
            "venue_id": 3289,
            "venue_name": "Citi Field"
        },
        {
            "away_id": 112,
            "away_name": "Chicago Cubs",
            "away_pitcher_note": "",
            "away_probable_pitcher": "Justin Steele",
            "away_score": 2,
            "current_inning": 2,
            "doubleheader": "N",
            "game_date": "2023-09-26",
            "game_datetime": "2023-09-26T23:20:00Z",
            "game_id": 716429,
            "game_num": 1,
            "game_type": "R",
            "home_id": 144,
            "home_name": "Atlanta Braves",
            "home_pitcher_note": "",
            "home_probable_pitcher": "Bryce Elder",
            "home_score": 0,
            "inning_state": "Top",
            "national_broadcasts": [
                "TBS (out-of-market only)"
            ],
            "series_status": null,
            "status": "In Progress",
            "summary": "2023-09-26 - Chicago Cubs (2) @ Atlanta Braves (0) (Top of the 2nd)",
            "venue_id": 4705,
            "venue_name": "Truist Park"
        },
        {
            "away_id": 133,
            "away_name": "Oakland Athletics",
            "away_pitcher_note": "",
            "away_probable_pitcher": "Paul Blackburn",
            "away_score": 0,
            "current_inning": 1,
            "doubleheader": "N",
            "game_date": "2023-09-26",
            "game_datetime": "2023-09-26T23:40:00Z",
            "game_id": 716421,
            "game_num": 1,
            "game_type": "R",
            "home_id": 142,
            "home_name": "Minnesota Twins",
            "home_pitcher_note": "",
            "home_probable_pitcher": "Bailey Ober",
            "home_score": 0,
            "inning_state": "Top",
            "national_broadcasts": [],
            "series_status": null,
            "status": "In Progress",
            "summary": "2023-09-26 - Oakland Athletics (0) @ Minnesota Twins (0) (Top of the 1st)",
            "venue_id": 3312,
            "venue_name": "Target Field"
        },
        {
            "away_id": 109,
            "away_name": "Arizona Diamondbacks",
            "away_pitcher_note": "",
            "away_probable_pitcher": "Zach Davies",
            "away_score": 0,
            "current_inning": 1,
            "doubleheader": "N",
            "game_date": "2023-09-26",
            "game_datetime": "2023-09-26T23:40:00Z",
            "game_id": 716427,
            "game_num": 1,
            "game_type": "R",
            "home_id": 145,
            "home_name": "Chicago White Sox",
            "home_pitcher_note": "",
            "home_probable_pitcher": "Jose Urena",
            "home_score": 0,
            "inning_state": "Bottom",
            "national_broadcasts": [],
            "series_status": null,
            "status": "In Progress",
            "summary": "2023-09-26 - Arizona Diamondbacks (0) @ Chicago White Sox (0) (Bottom of the 1st)",
            "venue_id": 4,
            "venue_name": "Guaranteed Rate Field"
        },
        {
            "away_id": 138,
            "away_name": "St. Louis Cardinals",
            "away_pitcher_note": "",
            "away_probable_pitcher": "Miles Mikolas",
            "away_score": 0,
            "current_inning": 1,
            "doubleheader": "N",
            "game_date": "2023-09-26",
            "game_datetime": "2023-09-26T23:40:00Z",
            "game_id": 716423,
            "game_num": 1,
            "game_type": "R",
            "home_id": 158,
            "home_name": "Milwaukee Brewers",
            "home_pitcher_note": "",
            "home_probable_pitcher": "Adrian Houser",
            "home_score": 0,
            "inning_state": "Middle",
            "national_broadcasts": [],
            "series_status": null,
            "status": "In Progress",
            "summary": "2023-09-26 - St. Louis Cardinals (0) @ Milwaukee Brewers (0) (Middle of the 1st)",
            "venue_id": 32,
            "venue_name": "American Family Field"
        },
        {
            "away_id": 140,
            "away_name": "Texas Rangers",
            "away_pitcher_note": "",
            "away_probable_pitcher": "Cody Bradford",
            "away_score": "0",
            "current_inning": "",
            "doubleheader": "N",
            "game_date": "2023-09-26",
            "game_datetime": "2023-09-27T01:38:00Z",
            "game_id": 716422,
            "game_num": 1,
            "game_type": "R",
            "home_id": 108,
            "home_name": "Los Angeles Angels",
            "home_pitcher_note": "",
            "home_probable_pitcher": "Reid Detmers",
            "home_score": "0",
            "inning_state": "",
            "national_broadcasts": [
                "MLBN (out-of-market only)"
            ],
            "series_status": "TEX leads 1-0",
            "status": "Pre-Game",
            "summary": "2023-09-26 - Texas Rangers @ Los Angeles Angels (Pre-Game)",
            "venue_id": 1,
            "venue_name": "Angel Stadium"
        },
        {
            "away_id": 135,
            "away_name": "San Diego Padres",
            "away_pitcher_note": "",
            "away_probable_pitcher": "Seth Lugo",
            "away_score": 0,
            "current_inning": 1,
            "doubleheader": "N",
            "game_date": "2023-09-26",
            "game_datetime": "2023-09-27T01:45:00Z",
            "game_id": 716437,
            "game_num": 1,
            "game_type": "R",
            "home_id": 137,
            "home_name": "San Francisco Giants",
            "home_pitcher_note": "",
            "home_probable_pitcher": "Kyle Harrison",
            "home_score": 0,
            "inning_state": "Top",
            "national_broadcasts": [
                "MLBN (out-of-market only)"
            ],
            "series_status": "SF leads 1-0",
            "status": "Pre-Game",
            "summary": "2023-09-26 - San Diego Padres @ San Francisco Giants (Pre-Game)",
            "venue_id": 2395,
            "venue_name": "Oracle Park"
        },
        {
            "away_id": 117,
            "away_name": "Houston Astros",
            "away_pitcher_note": "",
            "away_probable_pitcher": "Cristian Javier",
            "away_score": 0,
            "current_inning": 1,
            "doubleheader": "N",
            "game_date": "2023-09-26",
            "game_datetime": "2023-09-27T02:05:00Z",
            "game_id": 716425,
            "game_num": 1,
            "game_type": "R",
            "home_id": 136,
            "home_name": "Seattle Mariners",
            "home_pitcher_note": "",
            "home_probable_pitcher": "George Kirby",
            "home_score": 0,
            "inning_state": "Top",
            "national_broadcasts": [
                "TBS (out-of-market only)"
            ],
            "series_status": "HOU leads 1-0",
            "status": "Pre-Game",
            "summary": "2023-09-26 - Houston Astros @ Seattle Mariners (Pre-Game)",
            "venue_id": 680,
            "venue_name": "T-Mobile Park"
        }
          ]

      setScores(data);
    } catch (error) {
      setError(error.message);
    }}, []);

  useEffect(() => {
    fetchScores();
  }, [fetchScores]);

  // useEffect(() => {
  //   setScores([
  //     {
  //       away_id: 109,
  //       away_name: "Arizona Diamondbacks",
  //       away_pitcher_note: "",
  //       away_probable_pitcher: "Merrill Kelly",
  //       away_score: 4,
  //       current_inning: 9,
  //       doubleheader: "N",
  //       game_date: "2023-09-25",
  //       game_datetime: "2023-09-25T17:05:00Z",
  //       game_id: 716471,
  //       game_num: 1,
  //       game_type: "R",
  //       home_id: 147,
  //       home_name: "New York Yankees",
  //       home_pitcher_note: "",
  //       home_probable_pitcher: "Clarke Schmidt",
  //       home_score: 6,
  //       inning_state: "Top",
  //       losing_pitcher: "Kevin Ginkel",
  //       losing_team: "Arizona Diamondbacks",
  //       national_broadcasts: ["MLBN (out-of-market only)"],
  //       save_pitcher: "Clay Holmes",
  //       series_status: "NYY wins 2-1",
  //       status: "Final",
  //       summary:
  //         "2023-09-25 - Arizona Diamondbacks (4) @ New York Yankees (6) (Final)",
  //       venue_id: 3313,
  //       venue_name: "Yankee Stadium",
  //       winning_pitcher: "Ian Hamilton",
  //       winning_team: "New York Yankees",
  //     },
  //     {
  //       away_id: 140,
  //       away_name: "Texas Rangers",
  //       away_pitcher_note: "",
  //       away_probable_pitcher: "Jon Gray",
  //       away_score: "0",
  //       current_inning: "",
  //       doubleheader: "N",
  //       game_date: "2023-09-25",
  //       game_datetime: "2023-09-26T01:38:00Z",
  //       game_id: 716440,
  //       game_num: 1,
  //       game_type: "R",
  //       home_id: 108,
  //       home_name: "Los Angeles Angels",
  //       home_pitcher_note: "",
  //       home_probable_pitcher: "Patrick Sandoval",
  //       home_score: "0",
  //       inning_state: "",
  //       national_broadcasts: [],
  //       series_status: null,
  //       status: "Scheduled",
  //       summary: "2023-09-25 - Texas Rangers @ Los Angeles Angels (Scheduled)",
  //       venue_id: 1,
  //       venue_name: "Angel Stadium",
  //     },
  //     {
  //       away_id: 117,
  //       away_name: "Houston Astros",
  //       away_pitcher_note: "",
  //       away_probable_pitcher: "Justin Verlander",
  //       away_score: "0",
  //       current_inning: "",
  //       doubleheader: "N",
  //       game_date: "2023-09-25",
  //       game_datetime: "2023-09-26T01:40:00Z",
  //       game_id: 716436,
  //       game_num: 1,
  //       game_type: "R",
  //       home_id: 136,
  //       home_name: "Seattle Mariners",
  //       home_pitcher_note: "",
  //       home_probable_pitcher: "Luis Castillo",
  //       home_score: "0",
  //       inning_state: "",
  //       national_broadcasts: ["MLBN (out-of-market only)"],
  //       series_status: null,
  //       status: "Scheduled",
  //       summary: "2023-09-25 - Houston Astros @ Seattle Mariners (Scheduled)",
  //       venue_id: 680,
  //       venue_name: "T-Mobile Park",
  //     },
  //   ]);
  // }, []);

  console.log(scores);
  return (
    <div className={styles.scoretable}>
      {scores.length !== 0 ? (
        scores.map((score) => (
          <ScoreItem score={score} key={score["game_id"]} verbosity={verbosity}/>
        ))
      ) : (
        <span>No Games Today</span>
      )}
    </div>
  );
};

export default ScoreTable;
