// This page will be hard coded for now to only handle MLB score results from the MLB API.
"use client"; // haven't completely figured out best way to use client vs server components in nextjs just yet, probably just need a different component.

import { useCallback, useEffect, useState } from "react";
import ScoreItem from "./scoreitem";

const ScoreTable = (props) => {
  const [scores, setScores] = useState([]);

  // This will be commented out till the JSON files are corretly parsed. Dummy Date will be used for now.
  // const [error, setError] = useState(null);

  // const fetchScores = useCallback(async () => {
  //   try {
  //     const response = await fetch(
  //       "/api/mlb/schedule/today"
  //     );

  //     if (!response.ok) {
  //       throw new Error("Scores could not get retrieved!");
  //     }
  //     const data = await response.json();
  //     setScores(data);
  //   } catch (error) {
  //     setError(error.message);
  //   }}, []);


  // useEffect(() => {
  //   fetchScores();
  // }, [fetchScores]);

  useEffect( () => {setScores([
    {
      "away_id": 108,
      "away_name": "Los Angeles Angels",
      "away_pitcher_note": "",
      "away_probable_pitcher": "Kenny Rosenberg",
      "away_score": 1,
      "current_inning": 9,
      "doubleheader": "N",
      "game_date": "2023-09-23",
      "game_datetime": "2023-09-23T18:10:00Z",
      "game_id": 716465,
      "game_num": 1,
      "game_type": "R",
      "home_id": 142,
      "home_name": "Minnesota Twins",
      "home_pitcher_note": "",
      "home_probable_pitcher": "Sonny Gray",
      "home_score": 0,
      "inning_state": "Bottom",
      "losing_pitcher": "Sonny Gray",
      "losing_team": "Minnesota Twins",
      "national_broadcasts": [],
      "save_pitcher": "Carlos Estevez",
      "series_status": "Series tied 1-1",
      "status": "Final",
      "summary": "2023-09-23 - Los Angeles Angels (1) @ Minnesota Twins (0) (Final)",
      "venue_id": 3312,
      "venue_name": "Target Field",
      "winning_pitcher": "Kenny Rosenberg",
      "winning_team": "Los Angeles Angels"
    },
    {
      "away_id": 115,
      "away_name": "Colorado Rockies",
      "away_pitcher_note": "",
      "away_probable_pitcher": "Chris Flexen",
      "away_score": 3,
      "current_inning": 9,
      "doubleheader": "N",
      "game_date": "2023-09-23",
      "game_datetime": "2023-09-23T18:20:00Z",
      "game_id": 716469,
      "game_num": 1,
      "game_type": "R",
      "home_id": 112,
      "home_name": "Chicago Cubs",
      "home_pitcher_note": "",
      "home_probable_pitcher": "Marcus Stroman",
      "home_score": 6,
      "inning_state": "Top",
      "losing_pitcher": "Nick Mears",
      "losing_team": "Colorado Rockies",
      "national_broadcasts": [],
      "save_pitcher": "Jose Cuas",
      "series_status": "CHC wins 2-0",
      "status": "Final",
      "summary": "2023-09-23 - Colorado Rockies (3) @ Chicago Cubs (6) (Final)",
      "venue_id": 17,
      "venue_name": "Wrigley Field",
      "winning_pitcher": "Javier Assad",
      "winning_team": "Chicago Cubs"
    },
    {
      "away_id": 121,
      "away_name": "New York Mets",
      "away_pitcher_note": "",
      "away_probable_pitcher": "Jose Quintana",
      "away_score": 2,
      "current_inning": 6,
      "doubleheader": "N",
      "game_date": "2023-09-23",
      "game_datetime": "2023-09-23T20:05:00Z",
      "game_id": 716466,
      "game_num": 1,
      "game_type": "R",
      "home_id": 143,
      "home_name": "Philadelphia Phillies",
      "home_pitcher_note": "",
      "home_probable_pitcher": "Zack Wheeler",
      "home_score": 6,
      "inning_state": "Top",
      "national_broadcasts": [
        "MLBN (out-of-market only)"
      ],
      "series_status": "PHI leads 2-0",
      "status": "In Progress",
      "summary": "2023-09-23 - New York Mets (2) @ Philadelphia Phillies (6) (Top of the 6th)",
      "venue_id": 2681,
      "venue_name": "Citizens Bank Park"
    },
    {
      "away_id": 116,
      "away_name": "Detroit Tigers",
      "away_pitcher_note": "",
      "away_probable_pitcher": "Miguel Diaz",
      "away_score": 1,
      "current_inning": 6,
      "doubleheader": "N",
      "game_date": "2023-09-23",
      "game_datetime": "2023-09-23T20:07:00Z",
      "game_id": 716470,
      "game_num": 1,
      "game_type": "R",
      "home_id": 133,
      "home_name": "Oakland Athletics",
      "home_pitcher_note": "",
      "home_probable_pitcher": "Joe Boyle",
      "home_score": 2,
      "inning_state": "End",
      "national_broadcasts": [],
      "series_status": "Series tied 1-1",
      "status": "In Progress",
      "summary": "2023-09-23 - Detroit Tigers (1) @ Oakland Athletics (2) (End of the 6th)",
      "venue_id": 10,
      "venue_name": "Oakland Coliseum"
    },
    {
      "away_id": 141,
      "away_name": "Toronto Blue Jays",
      "away_pitcher_note": "",
      "away_probable_pitcher": "Hyun Jin Ryu",
      "away_score": 0,
      "current_inning": 6,
      "doubleheader": "N",
      "game_date": "2023-09-23",
      "game_datetime": "2023-09-23T20:10:00Z",
      "game_id": 716463,
      "game_num": 1,
      "game_type": "R",
      "home_id": 139,
      "home_name": "Tampa Bay Rays",
      "home_pitcher_note": "",
      "home_probable_pitcher": "Zack Littell",
      "home_score": 5,
      "inning_state": "Top",
      "national_broadcasts": [
        "MLBN (out-of-market only)",
        "MLB.tv Free Game"
      ],
      "series_status": "TOR leads 1-0",
      "status": "In Progress",
      "summary": "2023-09-23 - Toronto Blue Jays (0) @ Tampa Bay Rays (5) (Top of the 6th)",
      "venue_id": 12,
      "venue_name": "Tropicana Field"
    },
    {
      "away_id": 145,
      "away_name": "Chicago White Sox",
      "away_pitcher_note": "",
      "away_probable_pitcher": "Dylan Cease",
      "away_score": 0,
      "current_inning": 7,
      "doubleheader": "N",
      "game_date": "2023-09-23",
      "game_datetime": "2023-09-23T20:10:00Z",
      "game_id": 716468,
      "game_num": 1,
      "game_type": "R",
      "home_id": 111,
      "home_name": "Boston Red Sox",
      "home_pitcher_note": "",
      "home_probable_pitcher": "Nick Pivetta",
      "home_score": 0,
      "inning_state": "Top",
      "national_broadcasts": [],
      "series_status": "BOS leads 1-0",
      "status": "In Progress",
      "summary": "2023-09-23 - Chicago White Sox (0) @ Boston Red Sox (0) (Top of the 7th)",
      "venue_id": 3,
      "venue_name": "Fenway Park"
    },
    {
      "away_id": 158,
      "away_name": "Milwaukee Brewers",
      "away_pitcher_note": "",
      "away_probable_pitcher": "Brandon Woodruff",
      "away_score": 4,
      "current_inning": 6,
      "doubleheader": "N",
      "game_date": "2023-09-23",
      "game_datetime": "2023-09-23T20:10:00Z",
      "game_id": 716460,
      "game_num": 1,
      "game_type": "R",
      "home_id": 146,
      "home_name": "Miami Marlins",
      "home_pitcher_note": "",
      "home_probable_pitcher": "Jesus Luzardo",
      "home_score": 4,
      "inning_state": "Top",
      "national_broadcasts": [],
      "series_status": "MIL leads 1-0",
      "status": "In Progress",
      "summary": "2023-09-23 - Milwaukee Brewers (4) @ Miami Marlins (4) (Top of the 6th)",
      "venue_id": 4169,
      "venue_name": "loanDepot park"
    },
    {
      "away_id": 110,
      "away_name": "Baltimore Orioles",
      "away_pitcher_note": "",
      "away_probable_pitcher": "John Means",
      "away_score": 0,
      "current_inning": 1,
      "doubleheader": "N",
      "game_date": "2023-09-23",
      "game_datetime": "2023-09-23T22:10:00Z",
      "game_id": 716464,
      "game_num": 1,
      "game_type": "R",
      "home_id": 114,
      "home_name": "Cleveland Guardians",
      "home_pitcher_note": "",
      "home_probable_pitcher": "Cal Quantrill",
      "home_score": 0,
      "inning_state": "Top",
      "national_broadcasts": [],
      "series_status": "CLE leads 2-0",
      "status": "Pre-Game",
      "summary": "2023-09-23 - Baltimore Orioles @ Cleveland Guardians (Pre-Game)",
      "venue_id": 5,
      "venue_name": "Progressive Field"
    },
    {
      "away_id": 134,
      "away_name": "Pittsburgh Pirates",
      "away_pitcher_note": "",
      "away_probable_pitcher": "Bailey Falter",
      "away_score": 0,
      "current_inning": 1,
      "doubleheader": "N",
      "game_date": "2023-09-23",
      "game_datetime": "2023-09-23T22:40:00Z",
      "game_id": 716462,
      "game_num": 1,
      "game_type": "R",
      "home_id": 113,
      "home_name": "Cincinnati Reds",
      "home_pitcher_note": "",
      "home_probable_pitcher": "Connor Phillips",
      "home_score": 0,
      "inning_state": "Top",
      "national_broadcasts": [],
      "series_status": "PIT leads 1-0",
      "status": "Pre-Game",
      "summary": "2023-09-23 - Pittsburgh Pirates @ Cincinnati Reds (Pre-Game)",
      "venue_id": 2602,
      "venue_name": "Great American Ball Park"
    },
    {
      "away_id": 136,
      "away_name": "Seattle Mariners",
      "away_pitcher_note": "",
      "away_probable_pitcher": "Logan Gilbert",
      "away_score": 0,
      "current_inning": 1,
      "doubleheader": "N",
      "game_date": "2023-09-23",
      "game_datetime": "2023-09-23T23:05:00Z",
      "game_id": 716461,
      "game_num": 1,
      "game_type": "R",
      "home_id": 140,
      "home_name": "Texas Rangers",
      "home_pitcher_note": "",
      "home_probable_pitcher": "Jordan Montgomery",
      "home_score": 0,
      "inning_state": "Top",
      "national_broadcasts": [
        "MLBN (out-of-market only)"
      ],
      "series_status": "TEX leads 1-0",
      "status": "Pre-Game",
      "summary": "2023-09-23 - Seattle Mariners @ Texas Rangers (Pre-Game)",
      "venue_id": 5325,
      "venue_name": "Globe Life Field"
    },
    {
      "away_id": 118,
      "away_name": "Kansas City Royals",
      "away_pitcher_note": "",
      "away_probable_pitcher": "Jordan Lyles",
      "away_score": 0,
      "current_inning": 1,
      "doubleheader": "N",
      "game_date": "2023-09-23",
      "game_datetime": "2023-09-23T23:10:00Z",
      "game_id": 716455,
      "game_num": 1,
      "game_type": "R",
      "home_id": 117,
      "home_name": "Houston Astros",
      "home_pitcher_note": "",
      "home_probable_pitcher": "J.P. France",
      "home_score": 0,
      "inning_state": "Top",
      "national_broadcasts": [],
      "series_status": "KC leads 1-0",
      "status": "Pre-Game",
      "summary": "2023-09-23 - Kansas City Royals @ Houston Astros (Pre-Game)",
      "venue_id": 2392,
      "venue_name": "Minute Maid Park"
    },
    {
      "away_id": 138,
      "away_name": "St. Louis Cardinals",
      "away_pitcher_note": "",
      "away_probable_pitcher": "Jake Woodford",
      "away_score": 0,
      "current_inning": 1,
      "doubleheader": "N",
      "game_date": "2023-09-23",
      "game_datetime": "2023-09-24T00:40:00Z",
      "game_id": 716457,
      "game_num": 1,
      "game_type": "R",
      "home_id": 135,
      "home_name": "San Diego Padres",
      "home_pitcher_note": "",
      "home_probable_pitcher": "Nick Martinez",
      "home_score": 0,
      "inning_state": "Top",
      "national_broadcasts": [],
      "series_status": "SD leads 1-0",
      "status": "Pre-Game",
      "summary": "2023-09-23 - St. Louis Cardinals @ San Diego Padres (Pre-Game)",
      "venue_id": 2680,
      "venue_name": "Petco Park"
    },
    {
      "away_id": 137,
      "away_name": "San Francisco Giants",
      "away_pitcher_note": "",
      "away_probable_pitcher": "John Brebbia",
      "away_score": "0",
      "current_inning": "",
      "doubleheader": "N",
      "game_date": "2023-09-23",
      "game_datetime": "2023-09-24T01:10:00Z",
      "game_id": 716456,
      "game_num": 1,
      "game_type": "R",
      "home_id": 119,
      "home_name": "Los Angeles Dodgers",
      "home_pitcher_note": "",
      "home_probable_pitcher": "Clayton Kershaw",
      "home_score": "0",
      "inning_state": "",
      "national_broadcasts": [],
      "series_status": "Series tied 1-1",
      "status": "Pre-Game",
      "summary": "2023-09-23 - San Francisco Giants @ Los Angeles Dodgers (Pre-Game)",
      "venue_id": 22,
      "venue_name": "Dodger Stadium"
    },
    {
      "away_id": 144,
      "away_name": "Atlanta Braves",
      "away_pitcher_note": "",
      "away_probable_pitcher": "Kyle Wright",
      "away_score": "0",
      "current_inning": "",
      "doubleheader": "N",
      "game_date": "2023-09-23",
      "game_datetime": "2023-09-23T17:05:00Z",
      "game_id": 716467,
      "game_num": 1,
      "game_type": "R",
      "home_id": 120,
      "home_name": "Washington Nationals",
      "home_pitcher_note": "",
      "home_probable_pitcher": "Joan Adon",
      "home_score": "0",
      "inning_state": "",
      "national_broadcasts": [
        "MLBN (out-of-market only)"
      ],
      "series_status": "ATL leads 2-0",
      "status": "Postponed",
      "summary": "2023-09-23 - Atlanta Braves @ Washington Nationals (Postponed)",
      "venue_id": 3309,
      "venue_name": "Nationals Park"
    },
    {
      "away_id": 109,
      "away_name": "Arizona Diamondbacks",
      "away_pitcher_note": "",
      "away_probable_pitcher": "",
      "away_score": "0",
      "current_inning": "",
      "doubleheader": "N",
      "game_date": "2023-09-23",
      "game_datetime": "2023-09-23T17:05:00Z",
      "game_id": 716471,
      "game_num": 1,
      "game_type": "R",
      "home_id": 147,
      "home_name": "New York Yankees",
      "home_pitcher_note": "",
      "home_probable_pitcher": "",
      "home_score": "0",
      "inning_state": "",
      "national_broadcasts": [
        "MLBN (out-of-market only)"
      ],
      "series_status": "NYY leads 1-0",
      "status": "Postponed",
      "summary": "2023-09-23 - Arizona Diamondbacks @ New York Yankees (Postponed)",
      "venue_id": 3313,
      "venue_name": "Yankee Stadium"
    }
  ])}, []);


  console.log(scores);
  return (
    <div className="scoretable">
      {
        scores.map((score) => (
          <ScoreItem score={score} />
        ))
      }
    </div>
  );
};

export default ScoreTable;